(function(){"use strict";
var KEY="blastTierDataV7";
var BASE=["ltms","vanilla","uhc","pot","nethop","smp","sword","axe","mace"].map(function(id){return{id:id,name:id==="nethop"?"NethOP":id.charAt(0).toUpperCase()+id.slice(1),img:"assets/"+id+".png"};});
var DATA={players:[],tiers:[],customKits:[],messages:[]};var pending=[];
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||"null");if(x){DATA.players=Array.isArray(x.players)?x.players:[];DATA.tiers=Array.isArray(x.tiers)?x.tiers:[];DATA.customKits=Array.isArray(x.customKits)?x.customKits:[];DATA.messages=Array.isArray(x.messages)?x.messages:[];}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(DATA));return true}catch(e){alert("Browser storage is blocked. Enable site storage for GitHub Pages.");return false}}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[c]})}
function allKits(){return [{id:"overall",name:"Overall",img:"assets/overall.png"}].concat(BASE,DATA.customKits)}
function kit(n){return allKits().find(function(k){return k.name===n})||{name:n,img:"assets/overall.png"}}
window.openModal=function(id){var m=document.getElementById(id);if(m){m.classList.add("show");document.body.style.overflow="hidden";updateSelects()}};
window.closeModal=function(id){var m=document.getElementById(id);if(m)m.classList.remove("show");if(!document.querySelector(".modal.show"))document.body.style.overflow=""};
function updateSelects(){var pt=document.getElementById("playerTier"),ck=document.getElementById("comboKit"),ct=document.getElementById("comboTier"),tk=document.getElementById("tierKit");if(pt)pt.innerHTML='<option value="">No player tier</option>'+DATA.tiers.map(function(t){return'<option value="'+esc(t.name)+'">'+esc(t.name)+"</option>"}).join("");if(ck)ck.innerHTML=allKits().filter(function(k){return k.id!=="overall"}).map(function(k){return'<option value="'+esc(k.name)+'">'+esc(k.name)+"</option>"}).join("");if(ct)ct.innerHTML=DATA.tiers.length?DATA.tiers.map(function(t){return'<option value="'+esc(t.name)+'">'+esc(t.name)+"</option>"}).join(""):'<option value="">Add a tier first</option>';if(tk)tk.innerHTML=allKits().filter(function(k){return k.id!=="overall"}).map(function(k){return'<option value="'+esc(k.name)+'">'+esc(k.name)+"</option>"}).join("");renderPending()}
function renderPending(){var e=document.getElementById("chosen");if(!e)return;e.innerHTML=pending.map(function(x,i){return'<div><span>'+esc(x.kit)+' → <b class="tier">'+esc(x.tier)+'</b></span><button type="button" class="btn danger" data-remove="'+i+'">×</button></div>'}).join("")}
function addCombo(){var k=document.getElementById("comboKit"),t=document.getElementById("comboTier");if(!k||!t||!k.value||!t.value)return alert("Add a tier first.");if(pending.some(function(x){return x.kit===k.value}))return alert("This kit is already added.");pending.push({kit:k.value,tier:t.value});renderPending()}
function addPlayer(){var n=document.getElementById("playerName");if(!n||!n.value.trim())return alert("Enter player name.");if(DATA.players.some(function(p){return p.name.toLowerCase()===n.value.trim().toLowerCase()}))return alert("Player already exists.");if(!pending.length)return alert("Add at least one Kit + Tier.");var p={id:String(Date.now())+Math.random(),name:n.value.trim(),playerTier:(document.getElementById("playerTier")||{}).value||"",rank:(document.getElementById("playerRank")||{}).value||"Combat Master",points:Number((document.getElementById("playerPoints")||{}).value||0),region:(document.getElementById("playerRegion")||{}).value||"NA",combos:pending.slice(),skin:""};var f=document.getElementById("playerSkin"),file=f&&f.files&&f.files[0];function finish(){DATA.players.push(p);pending=[];save();var form=document.getElementById("playerForm");if(form)form.reset();window.closeModal("playerModal");refresh()};if(file){if(file.size>3145728)return alert("Skin must be under 3 MB.");var r=new FileReader();r.onload=function(){p.skin=r.result;finish()};r.onerror=function(){alert("Could not read the skin file.")};r.readAsDataURL(file)}else finish()}
function addTier(){var n=document.getElementById("tierName"),k=document.getElementById("tierKit");if(!n||!n.value.trim())return alert("Enter tier name.");if(!k||!k.value)return alert("Choose a kit.");if(DATA.tiers.some(function(t){return t.name.toLowerCase()===n.value.trim().toLowerCase()&&t.kit===k.value}))return alert("That tier already exists.");DATA.tiers.push({id:String(Date.now()),name:n.value.trim(),kit:k.value});save();window.closeModal("tierModal");var form=document.getElementById("addTierForm");if(form)form.reset();refresh()}
function addKit(){var n=document.getElementById("kitName");if(!n||!n.value.trim())return alert("Enter kit name.");if(allKits().some(function(k){return k.name.toLowerCase()===n.value.trim().toLowerCase()}))return alert("Kit already exists.");DATA.customKits.push({id:"custom-"+Date.now(),name:n.value.trim(),img:"assets/overall.png"});save();window.closeModal("kitModal");var form=document.getElementById("addKitForm");if(form)form.reset();refresh()}
function playerRow(p,i){var combos=(p.combos||[]).map(function(c){var k=kit(c.kit);return'<div class="combo"><img src="'+esc(k.img)+'" alt=""><span>'+esc(c.kit)+'<br><b class="tier">'+esc(c.tier)+'</b></span></div>'}).join("");return'<div class="player"><div class="place">'+(i+1)+'.</div><div class="skin">'+(p.skin?'<img src="'+p.skin+'" alt="">':"")+'</div><div><div class="name">'+esc(p.name)+'</div><div class="meta">◆ '+esc(p.rank)+' ('+(Number(p.points)||0)+' points)'+(p.playerTier?' • '+esc(p.playerTier):"")+'</div></div><div class="region">'+esc(p.region)+'</div><div class="combos">'+combos+'</div><button type="button" class="btn danger delete-player" data-delete="'+esc(p.id)+'">Delete</button></div>'}
function renderPlayers(e,filter){if(!e)return;var q=(document.getElementById("searchBox")||{}).value||"",a=DATA.players.filter(function(p){return p.name.toLowerCase().indexOf(q.toLowerCase())>=0});if(filter)a=a.filter(function(p){return(p.combos||[]).some(function(c){return c.kit===filter})});a.sort(function(x,y){return(Number(y.points)||0)-(Number(x.points)||0)});e.innerHTML=a.length?a.map(playerRow).join(""):'<div class="empty"><div><div style="font-size:50px">🏆</div><h2>No players yet!</h2><p>Add a player to start the rankings.</p></div></div>'}
function renderKits(){var e=document.getElementById("kitGrid");if(!e)return;e.innerHTML=allKits().filter(function(k){return k.id!=="overall"}).map(function(k){return'<a class="card" href="'+k.id+'.html"><img src="'+esc(k.img)+'"><h3>'+esc(k.name)+'</h3></a>'}).join("")}
function renderTiers(){var e=document.getElementById("tierGrid");if(!e)return;e.innerHTML=DATA.tiers.length?DATA.tiers.map(function(t){return'<div class="card"><h3>'+esc(t.name)+'</h3><div class="sub">'+esc(t.kit)+'</div></div>'}).join(""):'<div class="notice">No tiers added yet.</div>'}
function refresh(){load();updateSelects();var list=document.getElementById("playerList"),rank=document.getElementById("rankingList");if(list)renderPlayers(list,document.body.getAttribute("data-kit")||null);if(rank)renderPlayers(rank,null);renderKits();renderTiers();var stat=document.getElementById("statPlayers"),hero=document.getElementById("heroPlayer");if(stat)stat.textContent=DATA.players.length;if(hero)hero.textContent=DATA.players.length?DATA.players.slice().sort(function(a,b){return b.points-a.points})[0].name:"No players yet"}
function bind(){document.addEventListener("click",function(e){var open=e.target.closest("[data-open]"),close=e.target.closest("[data-close]"),remove=e.target.closest("[data-remove]"),del=e.target.closest("[data-delete]");if(open){e.preventDefault();window.openModal(open.getAttribute("data-open"))}if(close){e.preventDefault();window.closeModal(close.getAttribute("data-close"))}if(remove){pending.splice(Number(remove.getAttribute("data-remove")),1);renderPending()}if(del){if(confirm("Delete this player?")){DATA.players=DATA.players.filter(function(p){return String(p.id)!==String(del.getAttribute("data-delete"))});save();refresh()}}if(e.target.id==="addComboBtn")addCombo()});var pf=document.getElementById("playerForm");if(pf)pf.addEventListener("submit",function(e){e.preventDefault();addPlayer()});var tf=document.getElementById("addTierForm");if(tf)tf.addEventListener("submit",function(e){e.preventDefault();addTier()});var kf=document.getElementById("addKitForm");if(kf)kf.addEventListener("submit",function(e){e.preventDefault();addKit()});var s=document.getElementById("searchBox");if(s)s.addEventListener("input",refresh);document.addEventListener("keydown",function(e){if(e.key==="Escape"){document.querySelectorAll(".modal.show").forEach(function(m){m.classList.remove("show")});document.body.style.overflow=""}});document.querySelectorAll(".modal").forEach(function(m){m.addEventListener("click",function(e){if(e.target===m)window.closeModal(m.id)})})}
load();document.addEventListener("DOMContentLoaded",function(){bind();refresh()});
})();