const LOGOS={"overall": "assets/overall.png", "ltms": "assets/ltms.png", "vanilla": "assets/vanilla.png", "uhc": "assets/uhc.png", "pot": "assets/pot.png", "nethop": "assets/nethop.png", "smp": "assets/smp.png", "sword": "assets/sword.png", "axe": "assets/axe.png", "mace": "assets/mace.png"};
const NAMES={ltms:"LTMs",vanilla:"Vanilla",uhc:"UHC",pot:"Pot",nethop:"NethOP",smp:"SMP",sword:"Sword",axe:"Axe",mace:"Mace"};
const kits=[],tiers=[],players=[];let selectedLogo="sword";
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function makeTabs(){let a=[["overall","Overall"],...Object.keys(NAMES).map(k=>[k,NAMES[k]])];tabs.innerHTML=a.map((x,i)=>`<button class="tab ${i?"":"active"}"><img src="${x[0]=="overall"?LOGOS.overall:LOGOS[x[0]]}">${x[1]}</button>`).join("")}
function render(){kitGrid.innerHTML=kits.length?kits.map(k=>`<div class="kit"><img src="${LOGOS[k.icon]}">${esc(k.name)}</div>`).join(""):"<div style='grid-column:1/-1;text-align:center;color:#627a91'>No kits added yet.</div>";tierKit.innerHTML=kits.length?kits.map(k=>`<option>${esc(k.name)}</option>`).join(""):"<option>No kit</option>"}
function picker(){document.getElementById("picker").innerHTML=Object.keys(NAMES).map(k=>`<button class="${selectedLogo==k?"selected":""}" onclick="selectedLogo='${k}';picker()"><img src="${LOGOS[k]}"><small>${NAMES[k]}</small></button>`).join("")}
function openM(id){document.getElementById(id).classList.add("show");picker();render()}function closeM(){document.querySelectorAll(".modal").forEach(x=>x.classList.remove("show"))}
function addKit(){let n=kitName.value.trim();if(!n)return;kits.push({name:n,icon:selectedLogo});kitName.value="";selectedLogo="sword";closeM();render()}
function addTier(){let n=tierName.value.trim();if(!n)return;let k=kits.find(x=>x.name==tierKit.value);tiers.push({name:n,icon:k?k.icon:"sword"});tierName.value="";closeM()}
function addPlayer(){let n=playerName.value.trim();if(!n)return;let p={name:n,rank:rank.value,points:points.value||0,region:region.value,skin:""};let f=skin.files[0];let done=()=>{players.push(p);empty.style.display="none";playerList.innerHTML=players.map((x,i)=>`<div style="margin:7px 0;padding:14px;border:1px solid #1b2d40;border-radius:10px;background:#101b28;display:flex;align-items:center;gap:16px"><b style="font-size:26px">${i+1}.</b><div style="width:65px;height:56px;background:#18283a;border-radius:5px;overflow:hidden">${x.skin?`<img src="${x.skin}" style="width:100%;height:100%;object-fit:cover">`:""}</div><div><div style="font-size:20px;font-weight:900">${esc(x.name)}</div><div style="color:#7894af;margin-top:4px">◆ ${esc(x.rank)} (${esc(x.points)} points)</div></div><span style="margin-left:auto;background:#44202c;color:#ff7184;padding:11px;border-radius:8px">${x.region}</span></div>`).join("");closeM()};if(f){let r=new FileReader();r.onload=e=>{p.skin=e.target.result;done()};r.readAsDataURL(f)}else done()}
makeTabs();render();
