let players=[],kits=[],tiers=[],combos=[];
const icons={Sword:"⚔️",Axe:"🪓",Mace:"🔨",Pot:"🧪",UHC:"❤️",LTMs:"🎯",Vanilla:"🟩",NethOP:"🔥",SMP:"🌎"};
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');render()}
function openM(id){document.getElementById(id).classList.add('show');selects()}
function closeM(){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('show'))}
function selects(){pt.innerHTML='<option value="">No Tier</option>'+tiers.map(x=>`<option>${x.name}</option>`).join('');tk.innerHTML=kits.map(x=>`<option>${x.name}</option>`).join('');ck.innerHTML=kits.map(x=>`<option>${x.name}</option>`).join('');ct.innerHTML=tiers.map(x=>`<option>${x.name}</option>`).join('')}
function combo(){if(!ck.value||!ct.value)return;combos.push({kit:ck.value,tier:ct.value});chosen.innerHTML=combos.map((x,i)=>`<div>${icons[x.kit]||'◉'} ${x.kit} → <b>${x.tier}</b> <button onclick="combos.splice(${i},1);combo()">×</button></div>`).join('')}
function addKit(){let n=kn.value.trim();if(!n)return alert('Enter kit name');kits.push({name:n,logo:Object.keys(icons)[kits.length%Object.keys(icons).length]});kn.value='';closeM();render();selects()}
function addTier(){let n=tn.value.trim();if(!n)return alert('Enter tier name');tiers.push({name:n,kit:tk.value});tn.value='';closeM();selects()}
function addPlayer(){let n=pn.value.trim();if(!n)return alert('Enter player name');let p={name:n,tier:pt.value,rank:rank.value,points:points.value,region:region.value,combos:[...combos],skin:''};let f=skin.files[0];let done=()=>{players.push(p);combos=[];chosen.innerHTML='';pn.value='';skin.value='';closeM();render()};if(f){let r=new FileReader();r.onload=e=>{p.skin=e.target.result;done()};r.readAsDataURL(f)}else done()}
function del(i){players.splice(i,1);render()}
function playerHTML(p,i){let c=p.combos.length?p.combos.map(x=>`<div class="combo"><span class="icon">${icons[x.kit]||'◉'}</span>${x.kit}<span class="tier">${x.tier}</span></div>`).join(''):'<span class="muted">No kits</span>';return `<div class="player"><b>${i+1}.</b><div class="skin">${p.skin?`<img src="${p.skin}">`:''}</div><div class="pinfo"><strong>${p.name}</strong><div class="muted">${p.rank} • ${p.points} points${p.tier?' • '+p.tier:''}</div></div><span class="region">${p.region}</span><div class="combos">${c}</div><button class="delete" onclick="del(${i})">Delete</button></div>`}
function render(){renderTabs();renderKits();let e=document.getElementById('players');if(e)e.innerHTML=players.length?players.map(playerHTML).join(''):`<div class="empty"><div class="trophy">🏆</div><h2>No players yet!</h2><p>Add a player to start.</p></div>`;let r=document.getElementById('rankingList');if(r)r.innerHTML=players.length?[...players].sort((a,b)=>b.points-a.points).map(playerHTML).join(''):`<div class="empty"><h2>No rankings yet!</h2></div>`}
function renderTabs(){let e=document.getElementById('tabs');if(!e)return;e.innerHTML='<button onclick="page(\'home\')">🏆<br>Overall</button>'+kits.map(k=>`<button onclick="kitPage('${k.name.replace(/'/g,"\\'")}')">${icons[k.logo]||'◉'}<br>${k.name}</button>`).join('')}
function renderKits(){let e=document.getElementById('kits');if(!e)return;e.innerHTML=kits.length?kits.map(k=>`<div class="kitcard"><div class="icon">${icons[k.logo]||'◉'}</div>${k.name}</div>`).join(''):'<span class="muted">No kits added yet.</span>'}
function kitPage(n){page('kitpage');kitTitle.textContent=n;kitPlayers.innerHTML=players.filter(p=>p.combos.some(x=>x.kit===n)).map(playerHTML).join('')||`<div class="empty"><h2>No players in ${n} yet!</h2></div>`}
function send(){let x=chatInput.value.trim();if(!x)return;messages.innerHTML+=`<div class="msg">${x}</div>`;chatInput.value=''}
render();selects();